<?php

namespace Database\Seeders;

use App\Models\Countries;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = array(
            array('id' => '1', 'countryCode' => 'AD', 'name' => 'Andorra', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '2', 'countryCode' => 'AE', 'name' => 'United Arab Emirates', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '3', 'countryCode' => 'AF', 'name' => 'Afghanistan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '4', 'countryCode' => 'AG', 'name' => 'Antigua and Barbuda', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'countryCode' => 'AI', 'name' => 'Anguilla', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '6', 'countryCode' => 'AL', 'name' => 'Albania', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '7', 'countryCode' => 'AM', 'name' => 'Armenia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'countryCode' => 'AO', 'name' => 'Angola', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '9', 'countryCode' => 'AQ', 'name' => 'Antarctica', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '10', 'countryCode' => 'AR', 'name' => 'Argentina', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'countryCode' => 'AS', 'name' => 'American Samoa', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'countryCode' => 'AT', 'name' => 'Austria', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'countryCode' => 'AU', 'name' => 'Australia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '14', 'countryCode' => 'AW', 'name' => 'Aruba', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '15', 'countryCode' => 'AX', 'name' => 'Åland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '16', 'countryCode' => 'AZ', 'name' => 'Azerbaijan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '17', 'countryCode' => 'BA', 'name' => 'Bosnia and Herzegovina', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '18', 'countryCode' => 'BB', 'name' => 'Barbados', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '19', 'countryCode' => 'BD', 'name' => 'Bangladesh', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '20', 'countryCode' => 'BE', 'name' => 'Belgium', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '21', 'countryCode' => 'BF', 'name' => 'Burkina Faso', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '22', 'countryCode' => 'BG', 'name' => 'Bulgaria', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '23', 'countryCode' => 'BH', 'name' => 'Bahrain', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '24', 'countryCode' => 'BI', 'name' => 'Burundi', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '25', 'countryCode' => 'BJ', 'name' => 'Benin', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '26', 'countryCode' => 'BL', 'name' => 'Saint Barthélemy', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '27', 'countryCode' => 'BM', 'name' => 'Bermuda', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '28', 'countryCode' => 'BN', 'name' => 'Brunei', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '29', 'countryCode' => 'BO', 'name' => 'Bolivia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '30', 'countryCode' => 'BQ', 'name' => 'Bonaire', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '31', 'countryCode' => 'BR', 'name' => 'Brazil', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '32', 'countryCode' => 'BS', 'name' => 'Bahamas', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '33', 'countryCode' => 'BT', 'name' => 'Bhutan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '34', 'countryCode' => 'BV', 'name' => 'Bouvet Island', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '35', 'countryCode' => 'BW', 'name' => 'Botswana', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '36', 'countryCode' => 'BY', 'name' => 'Belarus', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '37', 'countryCode' => 'BZ', 'name' => 'Belize', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '38', 'countryCode' => 'CA', 'name' => 'Canada', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '39', 'countryCode' => 'CC', 'name' => 'Cocos [Keeling] Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '40', 'countryCode' => 'CD', 'name' => 'Democratic Republic of the Congo', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '41', 'countryCode' => 'CF', 'name' => 'Central African Republic', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '42', 'countryCode' => 'CG', 'name' => 'Republic of the Congo', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '43', 'countryCode' => 'CH', 'name' => 'Switzerland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '44', 'countryCode' => 'CI', 'name' => 'Ivory Coast', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '45', 'countryCode' => 'CK', 'name' => 'Cook Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '46', 'countryCode' => 'CL', 'name' => 'Chile', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '47', 'countryCode' => 'CM', 'name' => 'Cameroon', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '48', 'countryCode' => 'CN', 'name' => 'China', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '49', 'countryCode' => 'CO', 'name' => 'Colombia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '50', 'countryCode' => 'CR', 'name' => 'Costa Rica', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '51', 'countryCode' => 'CU', 'name' => 'Cuba', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '52', 'countryCode' => 'CV', 'name' => 'Cape Verde', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '53', 'countryCode' => 'CW', 'name' => 'Curacao', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '54', 'countryCode' => 'CX', 'name' => 'Christmas Island', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '55', 'countryCode' => 'CY', 'name' => 'Cyprus', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '56', 'countryCode' => 'CZ', 'name' => 'Czech Republic', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '57', 'countryCode' => 'DE', 'name' => 'Germany', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '58', 'countryCode' => 'DJ', 'name' => 'Djibouti', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '59', 'countryCode' => 'DK', 'name' => 'Denmark', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '60', 'countryCode' => 'DM', 'name' => 'Dominica', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '61', 'countryCode' => 'DO', 'name' => 'Dominican Republic', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '62', 'countryCode' => 'DZ', 'name' => 'Algeria', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '63', 'countryCode' => 'EC', 'name' => 'Ecuador', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '64', 'countryCode' => 'EE', 'name' => 'Estonia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '65', 'countryCode' => 'EG', 'name' => 'Egypt', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '66', 'countryCode' => 'EH', 'name' => 'Western Sahara', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '67', 'countryCode' => 'ER', 'name' => 'Eritrea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '68', 'countryCode' => 'ES', 'name' => 'Spain', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '69', 'countryCode' => 'ET', 'name' => 'Ethiopia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '70', 'countryCode' => 'FI', 'name' => 'Finland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '71', 'countryCode' => 'FJ', 'name' => 'Fiji', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '72', 'countryCode' => 'FK', 'name' => 'Falkland Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '73', 'countryCode' => 'FM', 'name' => 'Micronesia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '74', 'countryCode' => 'FO', 'name' => 'Faroe Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '75', 'countryCode' => 'FR', 'name' => 'France', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '76', 'countryCode' => 'GA', 'name' => 'Gabon', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '77', 'countryCode' => 'GB', 'name' => 'United Kingdom', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '78', 'countryCode' => 'GD', 'name' => 'Grenada', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '79', 'countryCode' => 'GE', 'name' => 'Georgia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '80', 'countryCode' => 'GF', 'name' => 'French Guiana', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '81', 'countryCode' => 'GG', 'name' => 'Guernsey', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '82', 'countryCode' => 'GH', 'name' => 'Ghana', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '83', 'countryCode' => 'GI', 'name' => 'Gibraltar', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '84', 'countryCode' => 'GL', 'name' => 'Greenland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '85', 'countryCode' => 'GM', 'name' => 'Gambia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '86', 'countryCode' => 'GN', 'name' => 'Guinea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '87', 'countryCode' => 'GP', 'name' => 'Guadeloupe', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '88', 'countryCode' => 'GQ', 'name' => 'Equatorial Guinea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '89', 'countryCode' => 'GR', 'name' => 'Greece', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '90', 'countryCode' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '91', 'countryCode' => 'GT', 'name' => 'Guatemala', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '92', 'countryCode' => 'GU', 'name' => 'Guam', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '93', 'countryCode' => 'GW', 'name' => 'Guinea-Bissau', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '94', 'countryCode' => 'GY', 'name' => 'Guyana', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '95', 'countryCode' => 'HK', 'name' => 'Hong Kong', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '96', 'countryCode' => 'HM', 'name' => 'Heard Island and McDonald Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '97', 'countryCode' => 'HN', 'name' => 'Honduras', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '98', 'countryCode' => 'HR', 'name' => 'Croatia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '99', 'countryCode' => 'HT', 'name' => 'Haiti', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '100', 'countryCode' => 'HU', 'name' => 'Hungary', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '101', 'countryCode' => 'ID', 'name' => 'Indonesia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '102', 'countryCode' => 'IE', 'name' => 'Ireland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '103', 'countryCode' => 'IL', 'name' => 'Israel', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '104', 'countryCode' => 'IM', 'name' => 'Isle of Man', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '105', 'countryCode' => 'IN', 'name' => 'India', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '106', 'countryCode' => 'IO', 'name' => 'British Indian Ocean Territory', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '107', 'countryCode' => 'IQ', 'name' => 'Iraq', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '108', 'countryCode' => 'IR', 'name' => 'Iran', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '109', 'countryCode' => 'IS', 'name' => 'Iceland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '110', 'countryCode' => 'IT', 'name' => 'Italy', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '111', 'countryCode' => 'JE', 'name' => 'Jersey', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '112', 'countryCode' => 'JM', 'name' => 'Jamaica', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '113', 'countryCode' => 'JO', 'name' => 'Jordan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '114', 'countryCode' => 'JP', 'name' => 'Japan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '115', 'countryCode' => 'KE', 'name' => 'Kenya', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '116', 'countryCode' => 'KG', 'name' => 'Kyrgyzstan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '117', 'countryCode' => 'KH', 'name' => 'Cambodia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '118', 'countryCode' => 'KI', 'name' => 'Kiribati', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '119', 'countryCode' => 'KM', 'name' => 'Comoros', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '120', 'countryCode' => 'KN', 'name' => 'Saint Kitts and Nevis', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '121', 'countryCode' => 'KP', 'name' => 'North Korea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '122', 'countryCode' => 'KR', 'name' => 'South Korea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '123', 'countryCode' => 'KW', 'name' => 'Kuwait', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '124', 'countryCode' => 'KY', 'name' => 'Cayman Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '125', 'countryCode' => 'KZ', 'name' => 'Kazakhstan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '126', 'countryCode' => 'LA', 'name' => 'Laos', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '127', 'countryCode' => 'LB', 'name' => 'Lebanon', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '128', 'countryCode' => 'LC', 'name' => 'Saint Lucia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '129', 'countryCode' => 'LI', 'name' => 'Liechtenstein', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '130', 'countryCode' => 'LK', 'name' => 'Sri Lanka', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '131', 'countryCode' => 'LR', 'name' => 'Liberia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '132', 'countryCode' => 'LS', 'name' => 'Lesotho', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '133', 'countryCode' => 'LT', 'name' => 'Lithuania', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '134', 'countryCode' => 'LU', 'name' => 'Luxembourg', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '135', 'countryCode' => 'LV', 'name' => 'Latvia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '136', 'countryCode' => 'LY', 'name' => 'Libya', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '137', 'countryCode' => 'MA', 'name' => 'Morocco', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '138', 'countryCode' => 'MC', 'name' => 'Monaco', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '139', 'countryCode' => 'MD', 'name' => 'Moldova', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '140', 'countryCode' => 'ME', 'name' => 'Montenegro', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '141', 'countryCode' => 'MF', 'name' => 'Saint Martin', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '142', 'countryCode' => 'MG', 'name' => 'Madagascar', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '143', 'countryCode' => 'MH', 'name' => 'Marshall Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '144', 'countryCode' => 'MK', 'name' => 'Macedonia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '145', 'countryCode' => 'ML', 'name' => 'Mali', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '146', 'countryCode' => 'MM', 'name' => 'Myanmar [Burma]', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '147', 'countryCode' => 'MN', 'name' => 'Mongolia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '148', 'countryCode' => 'MO', 'name' => 'Macao', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '149', 'countryCode' => 'MP', 'name' => 'Northern Mariana Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '150', 'countryCode' => 'MQ', 'name' => 'Martinique', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '151', 'countryCode' => 'MR', 'name' => 'Mauritania', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '152', 'countryCode' => 'MS', 'name' => 'Montserrat', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '153', 'countryCode' => 'MT', 'name' => 'Malta', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '154', 'countryCode' => 'MU', 'name' => 'Mauritius', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '155', 'countryCode' => 'MV', 'name' => 'Maldives', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '156', 'countryCode' => 'MW', 'name' => 'Malawi', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '157', 'countryCode' => 'MX', 'name' => 'Mexico', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '158', 'countryCode' => 'MY', 'name' => 'Malaysia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '159', 'countryCode' => 'MZ', 'name' => 'Mozambique', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '160', 'countryCode' => 'NA', 'name' => 'Namibia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '161', 'countryCode' => 'NC', 'name' => 'New Caledonia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '162', 'countryCode' => 'NE', 'name' => 'Niger', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '163', 'countryCode' => 'NF', 'name' => 'Norfolk Island', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '164', 'countryCode' => 'NG', 'name' => 'Nigeria', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '165', 'countryCode' => 'NI', 'name' => 'Nicaragua', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '166', 'countryCode' => 'NL', 'name' => 'Netherlands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '167', 'countryCode' => 'NO', 'name' => 'Norway', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '168', 'countryCode' => 'NP', 'name' => 'Nepal', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '169', 'countryCode' => 'NR', 'name' => 'Nauru', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '170', 'countryCode' => 'NU', 'name' => 'Niue', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '171', 'countryCode' => 'NZ', 'name' => 'New Zealand', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '172', 'countryCode' => 'OM', 'name' => 'Oman', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '173', 'countryCode' => 'PA', 'name' => 'Panama', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '174', 'countryCode' => 'PE', 'name' => 'Peru', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '175', 'countryCode' => 'PF', 'name' => 'French Polynesia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '176', 'countryCode' => 'PG', 'name' => 'Papua New Guinea', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '177', 'countryCode' => 'PH', 'name' => 'Philippines', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '178', 'countryCode' => 'PK', 'name' => 'Pakistan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '179', 'countryCode' => 'PL', 'name' => 'Poland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '180', 'countryCode' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '181', 'countryCode' => 'PN', 'name' => 'Pitcairn Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '182', 'countryCode' => 'PR', 'name' => 'Puerto Rico', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '183', 'countryCode' => 'PS', 'name' => 'Palestine', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '184', 'countryCode' => 'PT', 'name' => 'Portugal', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '185', 'countryCode' => 'PW', 'name' => 'Palau', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '186', 'countryCode' => 'PY', 'name' => 'Paraguay', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '187', 'countryCode' => 'QA', 'name' => 'Qatar', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '188', 'countryCode' => 'RE', 'name' => 'Réunion', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '189', 'countryCode' => 'RO', 'name' => 'Romania', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '190', 'countryCode' => 'RS', 'name' => 'Serbia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '191', 'countryCode' => 'RU', 'name' => 'Russia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '192', 'countryCode' => 'RW', 'name' => 'Rwanda', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '193', 'countryCode' => 'SA', 'name' => 'Saudi Arabia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '194', 'countryCode' => 'SB', 'name' => 'Solomon Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '195', 'countryCode' => 'SC', 'name' => 'Seychelles', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '196', 'countryCode' => 'SD', 'name' => 'Sudan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '197', 'countryCode' => 'SE', 'name' => 'Sweden', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '198', 'countryCode' => 'SG', 'name' => 'Singapore', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '199', 'countryCode' => 'SH', 'name' => 'Saint Helena', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '200', 'countryCode' => 'SI', 'name' => 'Slovenia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '201', 'countryCode' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '202', 'countryCode' => 'SK', 'name' => 'Slovakia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '203', 'countryCode' => 'SL', 'name' => 'Sierra Leone', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '204', 'countryCode' => 'SM', 'name' => 'San Marino', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '205', 'countryCode' => 'SN', 'name' => 'Senegal', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '206', 'countryCode' => 'SO', 'name' => 'Somalia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '207', 'countryCode' => 'SR', 'name' => 'Suriname', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '208', 'countryCode' => 'SS', 'name' => 'South Sudan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '209', 'countryCode' => 'ST', 'name' => 'São Tomé and Príncipe', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '210', 'countryCode' => 'SV', 'name' => 'El Salvador', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '211', 'countryCode' => 'SX', 'name' => 'Sint Maarten', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '212', 'countryCode' => 'SY', 'name' => 'Syria', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '213', 'countryCode' => 'SZ', 'name' => 'Swaziland', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '214', 'countryCode' => 'TC', 'name' => 'Turks and Caicos Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '215', 'countryCode' => 'TD', 'name' => 'Chad', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '216', 'countryCode' => 'TF', 'name' => 'French Southern Territories', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '217', 'countryCode' => 'TG', 'name' => 'Togo', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '218', 'countryCode' => 'TH', 'name' => 'Thailand', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '219', 'countryCode' => 'TJ', 'name' => 'Tajikistan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '220', 'countryCode' => 'TK', 'name' => 'Tokelau', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '221', 'countryCode' => 'TL', 'name' => 'East Timor', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '222', 'countryCode' => 'TM', 'name' => 'Turkmenistan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '223', 'countryCode' => 'TN', 'name' => 'Tunisia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '224', 'countryCode' => 'TO', 'name' => 'Tonga', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '225', 'countryCode' => 'TR', 'name' => 'Turkey', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '226', 'countryCode' => 'TT', 'name' => 'Trinidad and Tobago', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '227', 'countryCode' => 'TV', 'name' => 'Tuvalu', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '228', 'countryCode' => 'TW', 'name' => 'Taiwan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '229', 'countryCode' => 'TZ', 'name' => 'Tanzania', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '230', 'countryCode' => 'UA', 'name' => 'Ukraine', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '231', 'countryCode' => 'UG', 'name' => 'Uganda', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '232', 'countryCode' => 'UM', 'name' => 'U.S. Minor Outlying Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '233', 'countryCode' => 'US', 'name' => 'United States', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '234', 'countryCode' => 'UY', 'name' => 'Uruguay', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '235', 'countryCode' => 'UZ', 'name' => 'Uzbekistan', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '236', 'countryCode' => 'VA', 'name' => 'Vatican City', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '237', 'countryCode' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '238', 'countryCode' => 'VE', 'name' => 'Venezuela', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '239', 'countryCode' => 'VG', 'name' => 'British Virgin Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '240', 'countryCode' => 'VI', 'name' => 'U.S. Virgin Islands', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '241', 'countryCode' => 'VN', 'name' => 'Vietnam', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '242', 'countryCode' => 'VU', 'name' => 'Vanuatu', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '243', 'countryCode' => 'WF', 'name' => 'Wallis and Futuna', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '244', 'countryCode' => 'WS', 'name' => 'Samoa', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '245', 'countryCode' => 'XK', 'name' => 'Kosovo', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '246', 'countryCode' => 'YE', 'name' => 'Yemen', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '247', 'countryCode' => 'YT', 'name' => 'Mayotte', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '248', 'countryCode' => 'ZA', 'name' => 'South Africa', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '249', 'countryCode' => 'ZM', 'name' => 'Zambia', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '250', 'countryCode' => 'ZW', 'name' => 'Zimbabwe', 'created_at' => NULL, 'updated_at' => NULL)
        );

        foreach ($countries as $country) {
            $country_data = new Countries();
            $country_data->id = $country['id'];
            $country_data->countryCode =  $country['countryCode'];
            $country_data->name = $country['name'];
            $country_data->save();
        }
    }
}
